-- MySQL Script generated by MySQL Workbench
-- 07/30/16 13:19:52
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dmtools
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dmtools
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dmtools` DEFAULT CHARACTER SET utf8 ;
USE `dmtools` ;

-- -----------------------------------------------------
-- Table `dmtools`.`Campaign`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dmtools`.`Campaign` ;

CREATE TABLE IF NOT EXISTS `dmtools`.`Campaign` (
  `CampaignId` INT NOT NULL,
  `CampaignName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CampaignId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dmtools`.`Location`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dmtools`.`Location` ;

CREATE TABLE IF NOT EXISTS `dmtools`.`Location` (
  `LocId` INT NOT NULL,
  `CampaignId` INT NOT NULL,
  `LocName` VARCHAR(45) NOT NULL,
  `LocDesc` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`LocId`),
  INDEX `CampaignId_idx` (`CampaignId` ASC),
  CONSTRAINT `CampaignId`
    FOREIGN KEY (`CampaignId`)
    REFERENCES `dmtools`.`Campaign` (`CampaignId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dmtools`.`TableCategory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dmtools`.`TableCategory` ;

CREATE TABLE IF NOT EXISTS `dmtools`.`TableCategory` (
  `TableCategoryId` INT NOT NULL,
  `CategoryDesc` INT NOT NULL,
  PRIMARY KEY (`TableCategoryId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dmtools`.`TableDefinition`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dmtools`.`TableDefinition` ;

CREATE TABLE IF NOT EXISTS `dmtools`.`TableDefinition` (
  `TableId` INT NOT NULL,
  `TableCategoryId` INT NOT NULL,
  `TableName` VARCHAR(45) NOT NULL,
  `TableDieType` INT NOT NULL,
  `TableDieNum` INT NOT NULL,
  PRIMARY KEY (`TableId`),
  INDEX `TableCategoryId_idx` (`TableCategoryId` ASC),
  CONSTRAINT `TableCategoryId`
    FOREIGN KEY (`TableCategoryId`)
    REFERENCES `dmtools`.`TableCategory` (`TableCategoryId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dmtools`.`TableRoll`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dmtools`.`TableRoll` ;

CREATE TABLE IF NOT EXISTS `dmtools`.`TableRoll` (
  `TableRollId` INT NOT NULL,
  `TableId` INT NOT NULL,
  `MinRoll` INT NOT NULL,
  `MaxRoll` INT NOT NULL,
  `RollDesc` VARCHAR(45) NOT NULL,
  `SubTableId` INT NULL,
  `TableRollcol` VARCHAR(45) NULL,
  PRIMARY KEY (`TableRollId`),
  INDEX `TableTypeId_idx` (`TableId` ASC),
  INDEX `SubTableTypeId_idx` (`SubTableId` ASC),
  CONSTRAINT `TableTypeId`
    FOREIGN KEY (`TableId`)
    REFERENCES `dmtools`.`TableDefinition` (`TableId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `SubTableTypeId`
    FOREIGN KEY (`SubTableId`)
    REFERENCES `dmtools`.`TableDefinition` (`TableId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dmtools`.`TableLocation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dmtools`.`TableLocation` ;

CREATE TABLE IF NOT EXISTS `dmtools`.`TableLocation` (
  `TableLocationId` INT NOT NULL,
  `TableId` INT NULL,
  `LocId` INT NULL,
  PRIMARY KEY (`TableLocationId`),
  INDEX `LocId_idx` (`LocId` ASC),
  INDEX `TableId_idx` (`TableId` ASC),
  CONSTRAINT `LocId`
    FOREIGN KEY (`LocId`)
    REFERENCES `dmtools`.`Location` (`LocId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `TableId`
    FOREIGN KEY (`TableId`)
    REFERENCES `dmtools`.`TableDefinition` (`TableId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
